apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-marketplace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Karthik-Chowdary/local-k8s-platform.git
    targetRevision: main
    path: manifests/argo-marketplace
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-marketplace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
