apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echoserver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/Karthik-Chowdary/local-k8s-platform.git
    targetRevision: main
    path: manifests/echoserver
  destination:
    server: https://kubernetes.default.svc
    namespace: echoserver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
