apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argo-marketplace
    marketplace.argo/chart: redis
    marketplace.argo/repo: cloudpirates-redis
spec:
  project: default
  source:
    repoURL: https://github.com/Karthik-Chowdary/local-k8s-platform.git
    targetRevision: main
    path: manifests/redis
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
